name: CI

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/timbodv/tools_shell
          tags: |
            type=ref,event=tag
            type=sha
      #-
        #name: Set up QEMU
        #uses: docker/setup-qemu-action@v1
        # still learning, but I think this is for multi-arch builds https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
